# Generated by Django 2.1.7 on 2019-02-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=35)),
                ('profileImage', models.ImageField(upload_to='profile/')),
                ('city', models.CharField(max_length=20)),
            ],
        ),
    ]
