# Generated by Django 2.1.7 on 2019-02-27 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='profileArea',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
