# Generated by Django 2.1.7 on 2019-03-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0003_auto_20190301_1238'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=35)),
                ('profileImage', models.ImageField(upload_to='profile/')),
                ('city', models.CharField(max_length=20)),
                ('profileArea', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='OrganizerDetail',
        ),
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
