# Generated by Django 2.1.7 on 2019-04-19 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0004_auto_20190323_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userAddress', models.CharField(max_length=200)),
                ('userContact', models.IntegerField(max_length=12)),
                ('userEmailId', models.CharField(max_length=35)),
                ('userPassword', models.CharField(max_length=15)),
            ],
        ),
    ]
