# Generated by Django 2.1.7 on 2019-04-20 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0005_registermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userImage', models.ImageField(upload_to='profile/')),
                ('titele', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='RegistrationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=50)),
                ('userContact', models.IntegerField(max_length=12)),
                ('userEmailId', models.CharField(max_length=100)),
                ('userPassword', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='ProfileModel',
        ),
        migrations.DeleteModel(
            name='RegisterModel',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='userName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='discover.RegistrationModel'),
        ),
    ]
