# Generated by Django 2.1.7 on 2019-04-21 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discover', '0006_auto_20190420_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagemodel',
            old_name='userName',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='registrationmodel',
            name='userContact',
            field=models.IntegerField(),
        ),
    ]
